#
# Makefile for the Grand Unified Firmware Interface
#

CFLAGS_core.o += -DDEBUG
CFLAGS_of_protocol.o += -DDEBUG
CFLAGS_acpi_protocol.o += -DDEBUG

obj-$(CONFIG_GUFI) += core.o
obj-$(CONFIG_GUFI) += of_protocol.o
obj-$(CONFIG_GUFI) += acpi_protocol.o
